@startuml
participant Developer1 as "Java Developer 1"
participant Developer2 as "Java Developer 2"
participant Sysadmin as "SRE"

Developer1 -> Developer1 : Programar código y pruebas, \n depurar
Developer2 -> Developer2 : Programar código y pruebas, \n depurar
Sysadmin -> Sysadmin : Definir infraestructura como código
Sysadmin -> Sysadmin : Configurar\nel (los) servidores
Developer1 -> CVS : Gestionar versiones (Commit)
Developer2 -> CVS : Gestionar versiones (Commit)
Sysadmin -> CVS : Gestionar versiones (Commit)

database CVS as "CVS(Git)"

participant IC as "Servidor IC"

CVS -> IC : Obtener código
IC -> IC : Compilar
IC -> IC : Pruebas automáticas

database Artefacts as "Almacen Artefactos"
IC -> Artefacts : Almacenar artefactos (JAR, WAR, OCI)





participant Infra as "Infraestructura"

IC -> Infra : Desplegar infraestructura
IC -> Infra : Desplegar artefactos

Infra -> Sysadmin: Logs, métricas, estado
Sysadmin -> Infra: Acciones preventivas y correctivas

@enduml

